### ISSUE TITLE
Error on back-end from PostgresQueryRunner.ts file

### ISSUE THREAD

**Issue by mluik-git** [VladDrgm/Transcendence#198]
Encountering this error on pong_backend: 
[Nest] 26778  - 09/30/2023, 3:21:52 PM   ERROR [ExceptionsHandler] invalid input syntax for type integer: "1.9"
QueryFailedError: invalid input syntax for type integer: "1.9"
    at PostgresQueryRunner.query (.../pong_backend/src/driver/postgres/PostgresQueryRunner.ts:299:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at UpdateQueryBuilder.execute (.../pong_backend/src/query-builder/UpdateQueryBuilder.ts:145:33)
    at updateSubject (.../pong_backend/src/persistence/SubjectExecutor.ts:617:38)
    at async Promise.all (index 0)
    at SubjectExecutor.executeUpdateOperations (.../pong_backend/src/persistence/SubjectExecutor.ts:668:9)
    at SubjectExecutor.execute (.../pong_backend/src/persistence/SubjectExecutor.ts:148:9)
    at EntityPersistExecutor.execute (.../pong_backend/src/persistence/EntityPersistExecutor.ts:182:21)
    at MatchService.createMatch (.../pong_backend/src/modules/match/match.service.ts:57:5)
    at .../pong_backend/node_modules/@nestjs/core/router/router-execution-context.js:46:28

**Comment by VladDrgm** [comment]
Can you give additional details, please?

1) how to recreate issue
2) when is the error received - at which endpoint call
3) what is the expected behaviour

**Comment by mluik-git** [comment]
Ofc: Error occurs when finishing a game session and sending match data to DB. 
Expected behaviour is not seeing the error - it was working without error in previous versions.

**Comment by mluik-git** [comment]
Although the error message is displayed when sendin the match data, the fetch function itself gives a successful response, this error is displayed in addition.

**Comment by VladDrgm** [comment]
I think now it is fixed. Wait for 10 minutes after the time of this comment and it should be testable over the deployed version.
